mac_address: 00:11:60:01:00:12
virtual_interfaces:
  - name: rlr_c1_i1_viface1
    vlanid: 60
    addresses:
      - address: 10.0.60.12
        ipv4netmask: 255.255.255.0
    multicast:
      - 239.60.0.1
  - name: rlr_c1_i1_viface2
    vlanid: 40
    addresses:
      - address: 10.0.40.12
        ipv4netmask: 255.255.255.0
