"""Top-level package for flync-4-diagnostics."""

from .diagnostics_config import DiagnosticsConfig
from .doip import (
    DoIPConfig,
    DoIPDiscoveryDeployment,
    DoIPServerDeployment,
    DoIPTimingProfile,
    DoIPTimingProfileSet,
    DoIPTimings,
)
from .uds import (
    AccessProfile,
    ClearDiagnosticInformationService,
    DataIdentifier,
    DiagDataRecord,
    DiagField,
    DiagnosticSessionControlService,
    DiagnosticSessionDefinition,
    DiagnosticTroubleCode,
    DiagScaling,
    DIDIOControl,
    DTCGroup,
    DTCRecord,
    EcuResetService,
    GenericUDSService,
    ReadDataByIdentifierService,
    ReadDTCInformationService,
    RequestDownloadService,
    RequestUploadService,
    Routine,
    RoutineControlService,
    SecurityAccessService,
    SecurityLevelDeclaration,
    TransferMemoryRegion,
    TransferSetupService,
    UDSConfig,
    UDSServer,
    UDSServiceEntry,
    UDSSubfunction,
    UDSTimingProfile,
    UDSTimingProfileSet,
    UDSTimings,
)

KEY = "DIA"
__all__ = [
    "AccessProfile",
    "ClearDiagnosticInformationService",
    "DIDIOControl",
    "DTCGroup",
    "DTCRecord",
    "DataIdentifier",
    "DiagDataRecord",
    "DiagField",
    "DiagScaling",
    "DiagnosticSessionControlService",
    "DiagnosticSessionDefinition",
    "DiagnosticTroubleCode",
    "DiagnosticsConfig",
    "DoIPConfig",
    "DoIPDiscoveryDeployment",
    "DoIPServerDeployment",
    "DoIPTimingProfile",
    "DoIPTimingProfileSet",
    "DoIPTimings",
    "EcuResetService",
    "GenericUDSService",
    "ReadDTCInformationService",
    "ReadDataByIdentifierService",
    "RequestDownloadService",
    "RequestUploadService",
    "Routine",
    "RoutineControlService",
    "SecurityAccessService",
    "SecurityLevelDeclaration",
    "TransferMemoryRegion",
    "TransferSetupService",
    "UDSConfig",
    "UDSServer",
    "UDSServiceEntry",
    "UDSSubfunction",
    "UDSTimingProfile",
    "UDSTimingProfileSet",
    "UDSTimings",
]
