mac_address: 02:00:00:B1:00:01
virtual_interfaces:
  - name: vi0
    vlanid: 0
    addresses:
      - address: 10.0.0.14
        ipv4netmask: 255.255.255.0
  - name: vi10
    vlanid: 10
    addresses:
      - address: 10.0.10.14
        ipv4netmask: 255.255.255.0
