mac_address: 02:00:00:C0:00:05
mii_config:
  type: rmii
  speed: 100
  mode: mac
virtual_interfaces:
  - name: vi40
    vlanid: 0
    addresses:
      - address: 10.0.40.1
        ipv4netmask: 255.255.255.0
